# Generated by Django 2.2.7 on 2019-11-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('user_pw', models.CharField(max_length=255)),
                ('regist_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete_yn', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]